services:
  - type: web
    name: zkpulse
    runtime: node
    buildCommand: npm install && cd relayer && npm install && cd ..
    startCommand: node start-production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RPC_URL
        value: https://rpc.gigatheminter.com
      - key: WSS_URL
        value: wss://rpc.gigatheminter.com/ws
      - key: NETWORK_ID
        value: 369
      - key: RELAYER_PORT
        value: 4000
      # IMPORTANT: Add these in Render Dashboard as secrets:
      # - RELAYER_PRIVATE_KEY (your relayer's private key)
      # - RELAYER_ADDRESS (your relayer's address)
      # - CORS_ORIGIN (your domain, e.g. https://zkpulse.com)
      # - CUSTOM_DOMAIN (your domain, e.g. zkpulse.com)
    healthCheckPath: /api/health
    autoDeploy: true